# Generated by Django 4.2.29 on 2026-03-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0004_inspectionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='教师')),
                ('ai_attendance', models.IntegerField(verbose_name='实到人数')),
                ('ai_focus_rate', models.IntegerField(verbose_name='专注度评分')),
                ('inspector_name', models.CharField(max_length=50, verbose_name='巡课员')),
                ('score', models.IntegerField(default=5, verbose_name='评价得分')),
                ('tags', models.TextField(help_text='逗号分隔', verbose_name='评价标签')),
                ('comment', models.TextField(blank=True, verbose_name='详细评语')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='monitor.classroom')),
            ],
            options={
                'verbose_name': '巡课档案',
                'ordering': ['-created_at'],
            },
        ),
    ]
