# Generated by Django 4.2.29 on 2026-03-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_inspectionrecord'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectiontask',
            options={'ordering': ['-created_at'], 'verbose_name': '巡课历史记录', 'verbose_name_plural': '巡课历史管理'},
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='ai_attendance',
            field=models.IntegerField(default=0, verbose_name='实到人数'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='ai_focus_rate',
            field=models.IntegerField(default=0, verbose_name='专注度(%)'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='monitor.classroom', verbose_name='巡查教室'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='course_name',
            field=models.CharField(default='未知课程', max_length=100, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='巡课时间'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='inspector_name',
            field=models.CharField(default='管理员', max_length=50, verbose_name='巡课员'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='score',
            field=models.IntegerField(default=5, verbose_name='综合评分(1-5)'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='tags',
            field=models.TextField(blank=True, help_text='多个标签请用逗号分隔', verbose_name='评价标签'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='teacher_name',
            field=models.CharField(default='未知教师', max_length=50, verbose_name='任课教师'),
        ),
    ]
