# Generated by Django 4.2.29 on 2026-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_inspectiontask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontask',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否已复核'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='ai_attendance',
            field=models.IntegerField(default=0, verbose_name='实到人数(可复核)'),
        ),
    ]
