# Generated by Django 4.2.29 on 2026-03-19 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0003_inspectiontask_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontask',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='巡课人'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='room_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
    ]
