# Generated by Django 4.2.29 on 2026-03-19 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：201', max_length=50, verbose_name='教室名称')),
                ('building', models.CharField(help_text='如：明德楼', max_length=50, verbose_name='教学楼')),
            ],
            options={
                'verbose_name': '教室管理',
                'verbose_name_plural': '教室管理',
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('grade', models.IntegerField(help_text='如：2022', verbose_name='年级')),
                ('class_number', models.IntegerField(verbose_name='班级编号')),
            ],
            options={
                'verbose_name': '班级管理',
                'verbose_name_plural': '班级管理',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='任课教师')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='monitor.classroom', verbose_name='所属教室')),
                ('student_classes', models.ManyToManyField(related_name='courses', to='monitor.studentclass', verbose_name='上课班级')),
            ],
            options={
                'verbose_name': '课程排课',
                'verbose_name_plural': '课程排课',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='设备ID')),
                ('mock_image', models.ImageField(blank=True, null=True, upload_to='mock/images/', verbose_name='模拟图片素材')),
                ('mock_video', models.FileField(blank=True, null=True, upload_to='mock/videos/', verbose_name='模拟视频素材')),
                ('status', models.BooleanField(default=True, verbose_name='设备状态')),
                ('classroom', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='monitor.classroom', verbose_name='所属教室')),
            ],
        ),
    ]
