# Generated by Django 4.2.29 on 2026-03-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_studentclass_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='total_students',
            field=models.IntegerField(default=45, verbose_name='班级总人数'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='grade',
            field=models.IntegerField(verbose_name='年级'),
        ),
    ]
