# Generated by Django 4.2.29 on 2026-03-19 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_studentclass_total_students_alter_studentclass_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='任课教师')),
                ('inspector', models.CharField(default='管理员', max_length=50, verbose_name='巡课员')),
                ('attendance_count', models.IntegerField(verbose_name='实到人数')),
                ('focus_rate', models.IntegerField(verbose_name='专注度(%)')),
                ('rating', models.IntegerField(default=5, verbose_name='评分(1-5)')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='快捷标签')),
                ('comment', models.TextField(blank=True, verbose_name='详细评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.classroom', verbose_name='教室')),
            ],
            options={
                'verbose_name': '巡课记录',
                'verbose_name_plural': '巡课记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
