# Generated by Django 4.2.29 on 2026-04-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_inspectionrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': '监控管理', 'verbose_name_plural': '监控管理'},
        ),
    ]
